
import React, { useMemo } from 'react';
import { X, Printer, Box } from 'lucide-react';
import { CircuitComponent } from '../types';

interface BillOfMaterialsProps {
  components: CircuitComponent[];
  onClose: () => void;
}

interface BOMItem {
  name: string;
  typeId: string;
  description: string;
  quantity: number;
}

const BillOfMaterials: React.FC<BillOfMaterialsProps> = ({ components, onClose }) => {
  const bomItems = useMemo(() => {
    const items: Record<string, BOMItem> = {};

    components.forEach(comp => {
      // Human readable name formatting
      let rawType = comp.type.replace('wokwi-', '');
      let name = comp.label || rawType.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join(' ');

      const typeId = rawType;

      let description = '-';
      let key = typeId; // Grouping key

      // Distinguish components by key attributes
      if (comp.type.includes('resistor') && comp.attributes.value) {
        description = `${comp.attributes.value}Ω`;
        key = `${typeId}-${comp.attributes.value}`;
        name = "Resistor";
      } else if (comp.type.includes('led') && comp.attributes.color) {
        description = `${comp.attributes.color}`;
        key = `${typeId}-${comp.attributes.color}`;
        name = `LED (${comp.attributes.color})`;
      } else if (comp.type.includes('pushbutton')) {
        name = "Pushbutton";
      }

      if (!items[key]) {
        items[key] = {
          name: name,
          typeId: typeId,
          description: description,
          quantity: 0
        };
      }
      items[key].quantity++;
    });

    return Object.values(items).sort((a, b) => a.name.localeCompare(b.name));
  }, [components]);

  const totalQuantity = components.length;
  const generateDate = new Date().toLocaleString();

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>BOM - ZiroEDA</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          body { font-family: 'Courier New', monospace; padding: 20px; color: #000; max-width: 800px; margin: 0 auto; }
          h1 { margin-bottom: 5px; font-size: 24px; font-weight: bold; border-bottom: 2px solid #000; padding-bottom: 10px; }
          .subtitle { color: #444; margin-bottom: 30px; font-size: 14px; font-weight: bold; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
          th, td { text-align: left; padding: 10px 5px; border-bottom: 1px solid #ccc; }
          th { font-weight: bold; text-transform: uppercase; font-size: 12px; letter-spacing: 1px; }
          td { font-size: 14px; }
          .total-row td { font-weight: bold; border-top: 2px solid #000; border-bottom: none; padding-top: 15px; }
          .footer { margin-top: 50px; font-size: 10px; color: #666; border-top: 1px solid #eee; padding-top: 10px; display: flex; justify-content: space-between; }
          
          @media print {
            .no-print { display: none; }
            body { padding: 0; }
          }
          
          .no-print {
            text-align: center;
            margin-bottom: 20px;
          }
          .close-btn {
            background: #000;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-family: sans-serif;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
          }
        </style>
      </head>
      <body>
        <div class="no-print">
          <button class="close-btn" onclick="window.close()">Close Preview</button>
        </div>
        
        <h1>Bill of Materials</h1>
        <div class="subtitle">Generated by ZiroEDA</div>
        
        <table>
          <thead>
            <tr>
              <th>Component</th>
              <th>Type ID</th>
              <th>Description</th>
              <th style="text-align: right;">Quantity</th>
            </tr>
          </thead>
          <tbody>
            ${bomItems.map(item => `
              <tr>
                <td>${item.name}</td>
                <td>${item.typeId}</td>
                <td>${item.description}</td>
                <td style="text-align: right;">${item.quantity}</td>
              </tr>
            `).join('')}
            <tr class="total-row">
              <td colspan="3">Total Components</td>
              <td style="text-align: right;">${totalQuantity}</td>
            </tr>
          </tbody>
        </table>

        <div class="footer">
          <div>
            Generated on ${generateDate}<br>
            ZiroEDA - Prototype at the Speed of Thought
          </div>
        </div>
        <script>
           // Delay print to ensure rendering on mobile
           window.onload = function() { 
             setTimeout(function() { 
               window.print(); 
               // Do not auto-close, let user see the preview if print fails
             }, 500); 
           }
        </script>
      </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center">
      {/* Backdrop with Blur */}
      <div className="absolute inset-0 bg-black/60 backdrop-blur-md" onClick={onClose}></div>

      {/* Modal Container */}
      <div className="relative bg-[#13161c] w-[95%] md:w-full md:max-w-3xl rounded-xl border border-[#2d3748] shadow-[0_20px_60px_rgba(0,0,0,0.5)] overflow-hidden flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-200">

        {/* Header */}
        <div className="flex items-center justify-between px-4 md:px-6 py-5 border-b border-[#1e2229] bg-[#1a1d24]">
          <div className="flex items-center gap-4">
            <div className="p-2.5 bg-[#0891b2]/10 rounded-lg border border-[#0891b2]/20">
              <Box className="w-5 h-5 text-cyan-400" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white leading-none tracking-tight">Bill of Materials</h2>
              <p className="text-xs text-[#a0aec0] mt-1.5 font-medium">Project Component List</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={handlePrint}
              className="flex bg-[#0891b2] hover:bg-[#06b6d4] text-white text-xs font-bold px-2.5 md:px-4 py-2 rounded-lg transition-all shadow-lg shadow-cyan-900/20 items-center gap-2"
            >
              <Printer className="w-4 h-4" />
              <span className="hidden md:inline">Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 hover:bg-[#2d3748] text-[#718096] hover:text-white rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Table */}
        <div className="flex-1 overflow-auto p-0">
          <table className="w-full text-left border-collapse">
            <thead className="bg-[#0f1115] sticky top-0 z-10 shadow-sm">
              <tr className="border-b border-[#1e2229] text-[10px] font-bold text-[#718096] uppercase tracking-widest">
                <th className="py-4 px-4 md:px-6 font-bold">Component</th>
                <th className="py-4 px-4 md:px-6 font-bold hidden md:table-cell">Type ID</th>
                <th className="py-4 px-4 md:px-6 font-bold">Description</th>
                <th className="py-4 px-4 md:px-6 font-bold text-right">Qty</th>
              </tr>
            </thead>
            <tbody className="text-sm text-[#cbd5e0] font-mono divide-y divide-[#1e2229]">
              {bomItems.map((item, idx) => (
                <tr key={idx} className="hover:bg-[#1a1d24] transition-colors group">
                  <td className="py-3 px-4 md:px-6 font-medium text-white">{item.name}</td>
                  <td className="py-3 px-4 md:px-6 text-cyan-500/80 hidden md:table-cell">{item.typeId}</td>
                  <td className="py-3 px-4 md:px-6 text-[#a0aec0]">{item.description}</td>
                  <td className="py-3 px-4 md:px-6 text-right font-bold text-white bg-[#1a1d24]/50 group-hover:bg-[#1a1d24]">{item.quantity}</td>
                </tr>
              ))}
              {bomItems.length === 0 && (
                <tr>
                  <td colSpan={4} className="py-12 text-center text-[#4a5568] italic">
                    Circuit is empty. Add components to generate a BOM.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Footer Stats */}
        <div className="bg-[#0f1115] border-t border-[#1e2229]">
          <div className="px-6 py-3 flex items-center justify-between bg-[#0891b2]/10 border-b border-[#0891b2]/10">
            <span className="text-sm font-bold text-[#06b6d4]">Total Components</span>
            <span className="text-sm font-mono font-bold text-[#06b6d4]">{totalQuantity}</span>
          </div>
          <div className="px-6 py-4 text-center">
            <p className="text-[10px] text-[#4a5568] uppercase tracking-wider font-medium">Generated on {generateDate}</p>
          </div>
        </div>

      </div>
    </div>
  );
};

export default BillOfMaterials;
